name: pratudo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  dio: ^4.0.1
  dartz: ^0.10.0-nullsafety.2
  email_validator: ^2.0.1
  flutter_secure_storage: ^4.2.1
  fluttertoast: ^8.0.8
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  line_awesome_flutter: ^2.0.0
  mobx: ^2.0.5
  transparent_image: ^2.0.0
  percent_indicator: ^3.4.0
  shimmer: ^2.0.0
  easy_rich_text: ^1.0.1
  duration_picker: ^1.1.0+1
  lottie: ^1.2.1
  image_picker: ^0.8.4+4
  readmore: ^2.1.0

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.4
#  flutter_native_splash: ^1.2.0
#  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

#flutter_native_splash:
#  image: assets/images/logo.png
#  color: "#FF3B3B"
#  android: true
#
#flutter_icons:
#  android: true
#  image_path: "assets/images/launcher_icon.png"
#  adaptive_icon_background: "assets/images/background_icon.png"
#  adaptive_icon_foreground: "assets/images/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Worksans
      fonts:
        - asset: assets/fonts/worksans_light.ttf
          weight: 300
        - asset: assets/fonts/worksans_regular.ttf
          weight: 400
        - asset: assets/fonts/worksans_medium.ttf
          weight: 500
        - asset: assets/fonts/worksans_semibold.ttf
          weight: 600
